source "https://rubygems.org"

gem "jekyll", "~> 4.2"
gem "jekyll-data", "~> 1.1"
gem "jekyll-feed", "~> 0.17.0"
gem "jekyll-gist", "~> 1.5"
gem "jekyll-include-cache", "~> 0.2.1"
gem "jekyll-octicons", "~> 17.0"
gem "jekyll-paginate", "~> 1.1"
gem "jekyll-sitemap", "~> 1.4"
gem "jekyll-sass-converter", "~> 2"
